ros_verbosity_level: "DEBUG"
pcl_verbosity_level: "ERROR"
input_cloud_topic: "/camera/depth/color/points"
input_cloud_timeout_threshold: 7.0
voxel_grid_filter:
  leaf_sizes: [0.0000, 0.0000, 0.0000]
cropbox:
  enable: TRUE
  frame_id_norm: 1 # 0 - Optical Convention  1 - ROS convention
  horizontal_fov: 86.0 #degree
  vertical_fov: 56.0
  distance_range: 0.025 #toelrance range around the distance defined by the goal
sac_method:
  method_type: 0 # SAC_RANSAC  = 0; SAC_LMEDS   = 1; SAC_MSAC    = 2; SAC_RRANSAC = 3; SAC_RMSAC   = 4; SAC_MLESAC  = 5; SAC_PROSAC  = 6;
  model_type: 11
  axis: "x"
  normal_k_search : 7  #this parameter allow to set the same parameter to different cameras sensings
  normal_radius_search: 0 # 0.0005
  normal_distance_weight: 0.0005
  segmentation_threshold: 0.001
  inliers_threshold_weight: 0.01
  left_rate_to_all_candidates: 0.35
  max_iterations : 100000
  eps_angle: 5
plane_intersection:
  index_cloud_plane_a: 0
  index_cloud_plane_b: 1
  distance_to_line_threshold: 0.005
pose_filter:
  offset_threshold: [0, 0, 0] #[0.003, 0.0, 0.001] # BE AWARE IN WHICH REFENCE THE POINT CLOUD IS!
  welding_interval: 6
line_error:
  gt_line_frame_id: "wobj_weld"
  gt_line_axis: "x" #line direction
  gt_line_offset: 1 #line length

#MODEL TYPES INDEXES
#    SACMODEL_PLANE                 -0
#    SACMODEL_LINE,                 -1
#    SACMODEL_CIRCLE2D,             -2
#    SACMODEL_CIRCLE3D,             -3
#    SACMODEL_SPHERE,               -4
#    SACMODEL_CYLINDER,             -5
#    SACMODEL_CONE,                 -6
#    SACMODEL_TORUS,                -7
#    SACMODEL_PARALLEL_LINE,        -8
#    SACMODEL_PERPENDICULAR_PLANE,  -9
#    SACMODEL_PARALLEL_LINES,       -10
#    SACMODEL_NORMAL_PLANE,         -11
#    SACMODEL_NORMAL_SPHERE,        -12
#    SACMODEL_REGISTRATION,         -13
#    SACMODEL_REGISTRATION_2D,      -14
#    SACMODEL_PARALLEL_PLANE,       -15
#    SACMODEL_NORMAL_PARALLEL_PLANE,-16
#    SACMODEL_STICK                 -17
